CREATE TABLE IF NOT EXISTS staffs (
    id INT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    nic TEXT NOT NULL UNIQUE,
    license_no TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS doctors (
    id INT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public_health_midwives (
    id INT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    supervisor_id INT REFERENCES users(id) ON DELETE CASCADE
);